End of script 2

diff --git a/7_INIT/scripts/02 b/7_INIT/scripts/02
--- a/7_INIT/scripts/02
+++ b/7_INIT/scripts/02
@@ -1,21 +1,23 @@
 #!/bin/sh
+####################
 # Script de suppression d'un user logue sur la machine
-:'
+####################
+
 # Function - checks if given user is logged
 # Return value: 1 if yes, else 0
 is_logged()
 {
-	LIST=($(who | cut -f1 -d' '))
-	for user in ${LIST[*]}
+	for USER in $(who | cut -f1 -d' ')
 	do
-		if ["$1" -eq "$user"]
+		if [ "$1" = "$USER" ]
 		then
+			echo 1
 			return 1
 		fi
 	done
-	return 0
+	echo 0
 }
-'
+
 # Check arguments
 if [ $# -eq 0 ] || [ $# -ge 2 ]
 then
@@ -24,24 +26,29 @@ then
 fi
 
 # Check root 1
-:'
-if [ "$(id -u)" -ne "0" ]
+TEMP=$(id -u)
+if [ "$TEMP" -ne "0" ]
 then
 	echo "ERROR - permission denied."
 	exit 1
 fi
-'
 
 # Check root 2
-if [ "$(id -u $1)" -eq "0" ]
+TEMP=$(id -u $1 2> /dev/null)
+if [ "$TEMP" = "0" ]
 then
 	echo "ERROR - root can't be deleted"
 	exit 1
 fi
+if [ "$TEMP" = "" ]
+then
+	echo "ERROR - user does not exist"
+	exit 1
+fi
 
 # Check log
-is_logged $1
-if [$? -eq 1]
+TEMP=$(is_logged $1)
+if [ "$TEMP" = "1" ]
 then
 	userdel -fr $1
 	echo "SUCCESS - User deleted"
